name: Daily Blue Bombers Stats Update

on:
  schedule:
    # Run daily at 2 AM UTC (adjust timezone as needed)
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Create public directory
      run: mkdir -p public
      
    - name: Fetch and write all team stats
      run: node fetch-team-stats.js
      
    - name: Copy landing page
      run: cp public/index.html public/index.html.bak 2>/dev/null || true
      
    - name: Validate generated files
      run: |
        echo "Checking for required files..."
        required_files=("all_teams_2025_stats.json" "team_wpg_2025_stats.json" "all_teams_2025_stats.xml" "team_wpg_2025_stats.xml")
        missing_files=()
        
        for file in "${required_files[@]}"; do
          if [ ! -f "public/$file" ]; then
            missing_files+=("$file")
          fi
        done
        
        if [ ${#missing_files[@]} -gt 0 ]; then
          echo "❌ Missing required files: ${missing_files[*]}"
          exit 1
        else
          echo "✅ All required files present"
        fi
        
        echo "File sizes:"
        ls -lh public/*.json public/*.xml
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './public'
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4 